#ifndef __DlgConfigApp__
#define __DlgConfigApp__

/**
@file
Subclass of DialogConfigApp, which is generated by wxFormBuilder.
*/

#include "template_tiniLA.h"

/** Implementing DialogConfigApp */
class DlgConfigApp : public DialogConfigApp
{
protected:
   // Handlers for DialogConfigApp events.
   void OnButtonOKClick( wxCommandEvent& event );
   void OnButtonCancelClick( wxCommandEvent& event );
   
public:
   /** Constructor */
   DlgConfigApp( wxWindow* parent );

        void SetDevice( wxString str);
        wxString GetDevice( void);
};

#endif // __DlgConfigApp__
