#ifndef _FRAMEMAIN_H_
#define _FRAMEMAIN_H_

/*
 *
 * 2009-06-11 - ze Scrollbaru odebran SetFocus()
 */

/*
@file
Subclass of tiniLAFrame, which is generated by wxFormBuilder.
*/

#include "template_tiniLA.h"
#include "arraydef.h"

#include <wx/timer.h>
#include <wx/gauge.h>
#include <wx/statusbr.h>

enum CapState {
    CAPSTATE_IDLE,
    CAPSTATE_CAPTURING,
    CAPSTATE_STOPPING
};

/***********************************************************/
/* MyStatusBar */
/***********************************************************/
class MyStatusBar : public wxStatusBar
{
public:
    MyStatusBar(wxWindow *parent);
    virtual ~MyStatusBar();

    void UpdateClock();

    // event handlers
    void OnSize(wxSizeEvent& event);

  void SetGauge( unsigned int pos, unsigned int max);

private:
  wxGauge * m_statusGauge;

  DECLARE_EVENT_TABLE()
};


/** Implementing tiniLAFrame */
class FrameMain : public tiniLAFrame
{
protected:

   // Handlers for tiniLAFrame events.
   void OnSize( wxSizeEvent& event );
   void OnVertScroll( wxScrollEvent& event );
   void OnHorizScroll( wxScrollEvent& event );
   void OnExit( wxCommandEvent& event );
   void OnToolStartStop( wxCommandEvent& event );
   void OnZoomIn( wxCommandEvent& event );
   void OnZoomOut( wxCommandEvent& event );
   void OnZoom11( wxCommandEvent& event );
   void OnZoomFull( wxCommandEvent& event );
   void OnSetFocus( wxFocusEvent& event ) { SetFocus();}; // focus presunut ze scrollbaru na FrameMain

   void OnFileOpen( wxCommandEvent& event );
   void OnFileSave( wxCommandEvent& event );
   void OnFilePrint( wxCommandEvent& event );
   void OnConfigApp( wxCommandEvent& event );
   void OnHelpAbout( wxCommandEvent& event );
   void OnSampFreqChanged( wxCommandEvent& event ); 

   void OnThreadDataArrived( wxCommandEvent& event );

   void SetScrollSize( void);
   void SetZoom( void);
	void OnTimerEvent( wxTimerEvent& event);

   float m_zoom;
   wxString m_deviceString;

   bool m_threadcancelled;
   bool m_startpressed;
   bool m_stoppressed;
   unsigned int m_samplingfreq;
   ArrayOfSamples m_samples;
   MyStatusBar *m_statusBar;

   wxTimer m_timer;

private:
    long int m_cursorX;          // Cursor X position in samples
    bool m_cursorVisible;        // Cursor visibility flag
   bool m_deviceOpen;
   
public:
   /** Constructor */
   FrameMain( wxWindow* parent );
   ~FrameMain( void);

   bool ThreadCancelled( void) { return m_threadcancelled;};
   bool StartPressed( void) { return m_startpressed; };
   void UnPressStart( void) { m_startpressed = false; };
   bool StopPressed( void) { return m_stoppressed; };
   void UnPressStop( void);
   void GetTrigger( unsigned char *trigmask, unsigned char *trigval);

   /* returns position of the wxChoice - divider coded in VHDL */
   unsigned char GetSamplingFreq( void) { return m_samplingfreq; };

   void SetNewData(ArrayOfSamples arr);

   wxString GetUartName( void) { return m_deviceString; };
   void OnPanelMouseWheel(wxMouseEvent& event);
   void SetCursorPosition(long int samplePos);
   
};


#endif // __FrameMain__
